language: bash
sudo: required
dist: focal
services:
- docker

before_install:
- chmod +x docker-entrypoint.sh
- chmod +x envsubst-on-templates.sh
- chmod +x tune-worker-processes.sh
- chmod +x env.sh
- source env.sh
- docker build . -t $DOCKER_HUB_ID/nginx:$NGX_VERSION-rtmp-geoip2-alpine --no-cache

script:
- docker run -t --name webserver --rm  $DOCKER_HUB_ID/nginx:$NGX_VERSION-rtmp-geoip2-alpine nginx -v

after_success:
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- docker push $DOCKER_HUB_ID/nginx:$NGX_VERSION-rtmp-geoip2-alpine
