version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_ID
          password: $DOCKER_HUB_PASSWORD
    steps:
       - checkout
       - run: |
          chmod +x docker-entrypoint.sh
          chmod +x envsubst-on-templates.sh
          chmod +x tune-worker-processes.sh
          docker build . -t $DOCKER_HUB_ID/nginx:1.21.4-rtmp-geoip2-alpine --no-cache

  test:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_ID
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run: |
          docker run -t --name webserver --rm  $DOCKER_HUB_ID/nginx:1.21.4-rtmp-geoip2-alpine nginx -v
  
  deploy:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_ID
          password: $DOCKER_HUB_PASSWORD
    steps:
      - run: docker push $DOCKER_HUB_ID/nginx:1.21.4-rtmp-geoip2-alpine

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
